### ISSUE TITLE
Libmapstack ignoring `os`

### ISSUE THREAD

**Issue by tacerus** [lkubb/salt-podman-formula#1]
Hi,

I currently use this formula with some hardcoded patches on openSUSE and SLES. I would like to contribute upstream support and started adding a file `podman/parameters/os/SUSE.sls`:

```
---
values:
  lookup:
  ¦ required_pkgs:
  ¦ ¦ - git-core
  ¦ ¦ - python3-podman
  ¦ ¦ - python3-toml
  ¦ salt_compat:
  ¦ ¦ pips: []
  ¦ ¦ pkgs: []
  ¦ ¦ sockets:
  ¦ ¦ ¦ docker: /run/docker.sock
  ¦ ¦ ¦ podman: /run/podman/podman.sock
...
```

However, the debug output of libmapstack shows my custom settings to not have been applied:

```
[DEBUG   ] map.jinja: final configuration values:
values:
  added_in_defaults: defaults_value
  compose:
    install: false
    install_modules: false
    podman_compose_rev: false
  config:
    global:
      containers:
        containers: {}
        engine: {}
        machine: {}
        network: {}
        secrets: {}
        service_destinations: {}
      mounts: []
      policy:
        default:
        - type: insecureAcceptAnything
      registries:
        registry: []
        unqualified-search-registries:
        - docker.io
      storage:
        storage:
          driver: overlay
          graphroot: /var/lib/containers/storage
          options:
            additionalimagestores: []
          runroot: /run/containers/storage
    user: {}
  containers: {}
  debian_experimental: false
  debian_unstable: false
  install_method: pkg
  lookup:
    arch: amd64
    compose:
      docker:
        compose_version: 2.6.1
        latest:
          hash: https://github.com/docker/compose/releases/download/v{version}/docker-compose-linux-x86_64.sha256
          source: https://github.com/docker/compose/releases/download/v{version}/docker-compose-linux-x86_64
        legacy:
          hash: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-linux-x86_64.sha256
          source: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-linux-x86_64
        legacy_versions:
        - '1'
        - '2'
        - '3'
        - '4.0'
      podman:
        legacy_versions:
        - '1'
        - '2'
        - '3.0'
        pip: podman-compose
        pip_legacy: podman-compose==0.1.11
        repo: https://github.com/containers/podman-compose
    config: /etc/containers
    config_files:
      containers: containers.conf
      mounts: mounts.conf
      policy: policy.json
      registries: registries.conf
      seccomp: /usr/share/containers/seccomp.json
      storage: storage.conf
    containers:
      base: /opt/containers
    pkg:
      name: podman
    pkg_manager: zypper
    repos: {}
    required_pkgs: {}
    rootgroup: root
    salt_compat:
      pips:
      - docker
      pkgs:
      - python3-pip
      sockets:
        docker: /var/run/docker.sock
        podman: /var/run/podman/podman.sock
    service:
      name: podman
      path: /etc/systemd/system/{name}.service
      socket_path: /etc/systemd/system/{name}.socket
  salt_compat: false
  service_enable: false
  tofs:
    files_switch:
    - id
    - roles
    - os
    - os_family
  version: latest
  winner: defaults
[DEBUG   ] map.jinja: save parameters in variable 'mapdata'
[DEBUG   ] map.jinja: post-processing of 'mapdata'
```

Here is the complete output (3 month link, was too long for GitHub):

https://paste.opensuse.org/pastes/693fb1b96682

The `os` grain resolves to `SUSE` as expected:

```
# salt-call --local grains.get os
local:
    SUSE
```

I additionally tried:
- to remove the same keys from `podman/parameters/defaults.yaml`
- to add `os` to `tofs:files_switch`

I tried to understand how the mapping logic works but am not fully familiar how libmapstack is intended to operate and whether it's an issue with the code in this repository or with the libmapstack sources.

Would appreciate any help in having my `SUSE.sls` get read to correctly overwrite the desired default values.

**Comment by lkubb** [comment]
Thanks for your interest in contributing :)

```console
[DEBUG   ] map.jinja: load configuration values from podman/parameters/os/SUSE.yaml
[DEBUG   ] Could not find file 'salt://podman/parameters/os/SUSE.yaml' in saltenv 'base'
[DEBUG   ] map.jinja: load configuration values from podman/parameters/os/SUSE.yaml.jinja
[DEBUG   ] Could not find file 'salt://podman/parameters/os/SUSE.yaml.jinja' in saltenv 'base'
```

The file needs to have a `.yaml` (or `.yaml.jinja`) extension, not `.sls`.

`libmapstack` essentially works like this:

1. Check for a list of configuration sources, either specified in `<formularoot>/parameters/map_jinja.yaml` or `parameters/map_jinja.yaml` (there might be more places, not sure atm)
2. Try to render each possible source
3. If found, merge the data on top of the current ones (this merging can be influenced per source file)

(The details are explained [in the docs](https://github.com/lkubb/salt-podman-formula/blob/master/docs/map.jinja.rst) that were inherited from the `template-formula`.)

Note that `TOFS`/`files_switch` is unrelated to mapstack (it's a similar concept, but for parametrizing the `source` parameter in `file.managed` and similar states).

**Comment by tacerus** [comment]
I completely missed the wrong extension. With this corrected, it works as expected.
I used Jinja maps but `libmapstack` seems to come with various interesting additional logic. :) I will read the document (I had searched for documentation but it didn't occur to me to look here or in the template formula ...).
Thank you very much for the help and explanations, much appreciated!
